### ISSUE TITLE
semantic version

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#12]
I realize that this is highly experimental and pre-alpha with absolutely no pledge of a stable API, but should we start to version in `DESCRIPTION` and/or Github?

**Comment by juba** [comment]
In general I only use version numbers in reference to CRAN releases, _ie_ I only increment patch or minor numbers when releasing, and everything before the first release is just "pre-0.1".

But it may not be the best way to do it. Do you suggest we start tagging versions from time to time in git and/or `DESCRIPTION` independently of CRAN releases ?

**Comment by timelyportfolio** [comment]
I think your strategy will work great.  I might suggest once moderately stable and pre-CRAN marking with some version so that we can reference, but I don't think we are at that point.  Thanks for explaining your approach and intention.
