### ISSUE TITLE
wrap in htmlwidgets::JS()

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#14]
I wanted to note this discovery.  In some cases it appears we need to wrap the `input` as `htmlwidgets::JS()`.

```
library(robservable)
library(treemap)
library(d3r)
library(dplyr)

robservable(
  "@d3/zoomable-treemap",
  cell = "chart",
  input = list(
    data = data.frame(Titanic) %>%
      select(Class,Age,Survived,Sex,Freq) %>%
      rename(value = Freq) %>%
      d3_nest(value_cols="value", root="titanic") %>%
      htmlwidgets::JS()
  )
)
```

**Comment by juba** [comment]
I'm trying the example with and without `htmlwidgets::JS()` but can't spot any difference... 

Am I missing something ?

**Comment by timelyportfolio** [comment]
I couldn't make any sense of it yesterday.  Also working fine for me now as well so hopefully we can just close and move on. Thanks for checking.
