### ISSUE TITLE
document this is not an iframe

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#15]
I think it might be important for users to understand that these are not `iframe` meaning I think direct embed/incorporation is much more powerful.  For someone unfamiliar, I would guess that the assumption is `iframe`.

**Comment by juba** [comment]
Yes absolutely ! Keeping this open until we find a way to explain this in README or in a vignette.

**Comment by juba** [comment]
Closing it because I just added a note both at the start of the README and the introduction vignette. Feel free to reopen if you had something else in mind !
