### ISSUE TITLE
attach main to the widget instance

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#2]
I think it would be incredibly valuable to attach main to the widget instance so that a user can change at a later time through JavaScript or through proxy-like mechanism with Shiny.  Happy to submit pull if you agree that this would be helpful.  `leaflet` provides a function `getMap()` and many others just attach the object directly.  I have not decided if one or the other is a better approach.

**Comment by juba** [comment]
Yes, of course !

As you can see the code is very minimal for the moment, and you are much much more experienced than me both in JavaScript and htmlwidgets development, so feel free to suggest any improvement or to question any design decisions.

Thanks !

**Comment by juba** [comment]
Closing this since it has been implemented. I already used it to make cells updatable inside shiny apps. Thanks for the suggestion !
