### ISSUE TITLE
reference an unnamed cell

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#21]
apoligies if this is already supported...but referencing unnamed cells would be very helpful.  I found

- https://talk.observablehq.com/t/how-to-get-a-cell-s-name/1246/11 
- https://talk.observablehq.com/t/feature-request-deep-links/607/6

 that might help unlock the secret.

**Comment by juba** [comment]
No it's not already supported, and I thought it was not possible as unnamed cells seem not to be accessible via the runtime API. The workaround in the README for now is to fork the notebook and name the cell.

If there's a way, that would indeed be great as notebooks don't necessarily name their main output cell.

**Comment by timelyportfolio** [comment]
Unfortunately, I have concluded that unnamed are not currently supported very well as described in https://github.com/observablehq/runtime#runtime_module (bold-mine).

> If an observer factory function is specified, it is called for each named variable in the returned module, being **passed the variable’s name**. The standard inspector is available as a ready-made observer: it displays DOM elements “as-is” and renders interactive displays for other arbitrary values such as numbers and objects.

However, after a little experimentation, I wonder if we should include an argument (want to be careful that we don't over-argument though) like `include_unnamed` that would include all unnamed cells.  As a prototype, we could move the append of `output_divs` to `build_inspector` and change the `build_inspector` function to something like:

```
            return (name) => {
                if (this.params.cell.includes(name)) {
                    return new observablehq.Inspector(output_divs.get(name));
                    this.el.appendChild(output_divs.get(name))
                }
                if ( (typeof(name) === "undefined" || name === "") && this.params.include_unnamed === true ){
                    const div = document.createElement("div");
                    this.el.appendChild(div);
                    return new observablehq.Inspector(div);
                }

            }
```

We could supplement with some naming, so a user could potentially selectively reference or hide unnamed `div`.

Another option would be to add a counter mechanism so that users would be able to provide an index/number in addition to a `name`.

**Comment by juba** [comment]
Adding the ability to render unnamed cells seems useful. It moves the workaround complexity from Observable (forking the notebook and naming cells) to R, which could be suitable for people who are not already familiar with Observable. It seems to me that the most frequent use of such a feature would be when the main output cell is not named, which is quite frequent. It should be less useful to be able to modify these cells values... 

Your solution is really interesting, I didn't think of the option to include all the unnamed cells. Being able to show/hide some of these would certainly be welcome, but in the cases where the only unnamed cell is the main output one, displaying all unnamed cells would make it work almost "out of the box".

I think this may impact the `create_output_divs` function too ? I moved it outside of `build_inspector` for code clarity, but you may have to move back output div creation into it (which is not a problem).

**Comment by timelyportfolio** [comment]
Thanks for your thoughts.  I agree that unnamed will almost always be `html` and `md` outputs.  My guess is that many users might want to hide `md` but show `html`.

I'll try to assemble a pull that would allow some control over unnamed cells, resolve any issues with `create_output_divs`, and hopefully create a mechanism through which a user could reference unnamed cells.  I think I will have time over the weekend.

**Comment by timelyportfolio** [comment]
@juba I just noticed your commit to Readme.  I had not realized that you were intentionally trying not to show until the user was able to update values.  I like this idea.

**Comment by juba** [comment]
In fact I think it was more a bad sentence than a feature idea :-) 

I originally wrote it like this because I thought about updating the values at widget creation, without taking shiny apps into account... So it was really just a description of when the update takes place more than an idea of delaying something until update is possible.

**Comment by timelyportfolio** [comment]
@juba ok, would be nice but I think very difficult to accomplish reliably.  Guess I'll close this issue now.  Feel free to reopen.
