### ISSUE TITLE
name for `cell` argument

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#25]
In #23 we started to discuss whether the `cell` argument should be something else.  I think `cell` is fine, but that is likely because I use Observablehq quite a bit, and the term is familiar to me.  We could opt for a verb similar to `hide`.  I included a couple of options:

- show
- render
- include

I do not have a strong opinion.  If we change, we will need to make sure we change the examples.

**Comment by juba** [comment]
I agree with the idea to use a verb, seems more natural and coherent with `hide`. I've got a small doubt on `show`, because there are cases when we want to include a cell without showing it (in this case the cell would be both in `show` and `hide`, which feels a little strange). Both `include` and `render` seem good to me... Maybe `include` is more "natural" ?

**Comment by timelyportfolio** [comment]
good point on `show` and I agree `include` seems like a good choice.  `render` I think carries much closer association with `show`.  Will try to think of a couple of others (hopefully shorter) verbs.  I guess `add` might be an option.

**Comment by timelyportfolio** [comment]
join, bind, link, connect

**Comment by juba** [comment]
Thanks for your propositions ! I think I've got a small preference for `include`. `add` is shorter, but it seems to me that by conveying the idea of adding something it is not totally coherent with the fact that it is rather "selects" specific cells...

But maybe you find that `include` is too long ?

I'm less convinced by join, bind, link and connect, each one seems to carry a slightly different meaning...

**Comment by timelyportfolio** [comment]
@juba `include` works for me.   Want me to make the changes in function, JS, documentation, and examples?

**Comment by juba** [comment]
If you have the time and are ok to do it, yes !

I can do it in the vignettes if you want to share the "burden".

**Comment by timelyportfolio** [comment]
@juba I'm happy to change all as long as next day or so is an acceptable time for completion.

**Comment by timelyportfolio** [comment]
@juba I hope I changed all `cell` to `include`.  I tested all examples, vignettes, and rmarkdown that I found in the repo, and all seemed to work.  Since this is breaking I incremented to `0.2.0` and updated package date.  Please check if you have time that I successfully rid everything of `cell =`.  Thanks.

**Comment by timelyportfolio** [comment]
@juba sorry I messed up with `origin` and `upstream` and ended up needing to push to `master`.  Hope this doesn't pose any problems.

**Comment by juba** [comment]
Thanks a lot !
