### ISSUE TITLE
Proofread the README

### ISSUE THREAD

**Issue by juba** [juba/robservable#34]
@timelyportfolio Would you be ok, when you have time, to proofread the README file ? It has been very useful for the vignettes, and I wouldn't want potential users to stumble upon a big spelling mistake :)

Maybe after this we would not be far from a CRAN release ?

**Comment by timelyportfolio** [comment]
Very lightly proofread readme.md and made minor corrections.  Yes, I agree we are close to CRAN.  Would you be able to test on winbuilder and rhub?  If not I am happy to do.

**Comment by juba** [comment]
Thanks for the README fixes. I tend to rely on Github actions check results, but if you want to submit to winbuilder and r-hub, it would be fine and may avoid problems when submitting.

**Comment by juba** [comment]
I had some time this morning, and I submitted the package to both r-hub and win-builder, as you suggested. The result was clean except for a quick fix in the `Description` field.

Do you think I could start pushing the package to CRAN ?

**Comment by timelyportfolio** [comment]
@juba In my experience winbuilder is the strictest, so if it passed there, I would say `robservable` is ready for a CRAN submission.

**Comment by juba** [comment]
Yes, I think you're right, win-builder made me a note about a possible misspelled word in DESCRIPTION that I didn't have with the other checks (I think).

Well, I'll close this issue, and let's go to CRAN then... :)
