### ISSUE TITLE
Instance customization by d3 not working

### ISSUE THREAD

**Issue by draben** [juba/robservable#35]
**Use case:**  create a visual template on Observable, instantiate it in Rmd several times, use <script> tags in the Rmd containing d3 code to customize each instance.  For example, at the bottom of the Rmd, I have something like the code below.  For larger customizations, I will use dedicated/sourced js files.

```html
<script>
```
```js
window.addEventListener("load", (event) => {
  console.log(d3.version);
  d3.selectAll("#instance path")
    .on("mouseover", (event, d) => {d3.select(event.target).style("stroke", "black")})
    .on("mouseout", (event, d) => {d3.select(event.target).style("stroke", "white")});
})
```
```html
</script>
```
**Issue:** No mouseover/mouseout behavior works.  In the console, I **do** see 6.1.1 as expected (I am loading d3 in the ```<head>```).  If I copy/paste that d3 statement into the Chrome console after the page loads, it works fine.  The same issue persists with or without the window event listener.

**Workaround:** For the time being, I have added a js_customization cell to the template on Observable which gets executed with eval() when it is defined.  Then I'm passing d3 code by way of an input parameter.  While functional, passing code as text and evaluating it is not ideal.

**Request:** What is the recommended/supported approach to customize individual instances?

**Comment by juba** [comment]
Thanks for taking the time to report this issue.
The problem is that at the `load` window event, the embedded cells are not yet resolved, so the `d3.selectAll("#instance path")` selects nothing. One dirty workaround could be to wait for some seconds before running the code, but it would be much cleaner to have a sort of event to be listened to that would indicate when all cells are ready...

**Comment by draben** [comment]
Thanks for responding so quickly.  If you're willing to consider more input:

One of the primary benefits of Observable is reusability, which implies instance customization.  Rather than workarounds, can you please consider wrapping your call to `htmlwidgets::createWidget()` inside `htmlwidgets::onRender()` either always or under certain circumstances?  I can imagine several reasonable implementation options.  Here are just two examples:
* Do what you suggest&mdash;In the presence of `elementId`, use `onRender()`'s `jsCode` argument create a `CustomEvent` named 'elemendId' that fires when the widget is rendered
* Add a new optional parameter to `robservable()` accepting a vector of JS functions to execute. Use `onRender()`'s `jsCode` and `data` arguments to fire each user-supplied JS function.  Maybe these could default to executing asynchronously via Promise chains, or synchronously when requested by a second toggling parameter.

**On workarounds:**
Pausing for a fixed amount of time is no good.  The delay may be insufficient.  Pausing for too long will result in poor usability for page visitors.

My current workaround is to 1) create a `js_customization = undefined` cell in observable, 2) add `if (if_customization) eval(js_customization)` in any cell I might export, and 3) pass JS as text via the input parameter of `robservable()`.

**This is still no good** for at least these reasons (probably many more, I'm a n00b):
* It requires changing your observable pages to include `js_customization` in many places
* It requires forking copies of other peoples' pages so that you can change them; this loses any updates people make to those pages
* It requires supplying JS as text.  For short code, this is no biggie.  For long code, there's unnecessary conversions needed to keep JS context highlighting (i.e., put JS in somefile.js for context highlighting, read in somefile.js as text, pass through robservable() as an input)

**Comment by juba** [comment]
Regarding `onRender()`, there's no need to put this in the package code I think, you can wrap your `robservable()` call yourself. However, and unfortunately, I don't think it can be a solution : `onRender` waits for the widget to be rendered, but not for the notebook cells to be computed and displayed. So I think you will have the same problem than with the `load` event... 

I agree on your points on the workarounds. Just for the second one, I think that by importing a notebook and adding your code instead of forking it there could be a way to customize it without loosing upstream updates.

One better workaround could be to explicitly wait for something, like an element to be present, for example something like : 

```js
let delay = function(duration, value) {
  return new Promise(function(resolve) {
    setTimeout(function() {
      resolve(value);
    }, duration);
  });
}

async function init() {
  while (!(document.querySelector("#instance path"))) {
    await delay(500);
  }
  console.log("ready");
   d3.selectAll("rect")
    .on("mouseover", (event, d) => {d3.select(event.target).style("stroke", "black")})
    .on("mouseout", (event, d) => {d3.select(event.target).style("stroke", "white")});
}

init()
```

**Comment by draben** [comment]
Thank you for your consideration!

**Comment by juba** [comment]
You're welcome ! I hope the given workaround will work for you, if that is not the case don't hesitate to reopen the issue.

And if I find a better and cleaner solution I'll try to post it here, too.

**Comment by draben** [comment]
At the risk of belaboring the conversation, I don't consider the delay/async init() option you provided to be a valid workaround.  Or at least not in a good number of cases.  The statement `document.querySelector(...)` will be truthy if *something* is returned, but it needs to be truthy only when *all of the elements* are returned.  Suppose a cell is generating 10000 elements but only 500 exist when delay() completes...

In the cases where the number of elements in the selection is known in advance, I suppose the while condition could change to test the full set of objects have been created.  However, there are lots of use cases where this number will not be known in advance.

I'll keep injecting JS into the Observable cells.  Perhaps it won't be as bad as I'm thinking it will be.

**Comment by juba** [comment]
I completely agree with you, this is a workaround and not really workable in your example.

I posted a question on the Observable forum and I think there are some promising leads : I'll take a look at it.

https://talk.observablehq.com/t/detecting-when-cells-are-ready-when-embedding-a-notebook/4089/4

**Comment by juba** [comment]
I just added custom event emission for the different notebook cell states. So for example, if you have a named cell `chart`, you can listen to the following event attached to `document` and emitted when the cell is at state 'pending', 'fulfilled' or 'rejected' : 

- `robservable-chart-pending`
- `robservable-chart-fulfilled`
- `robservable-chart-rejected`

So I think you should be able to do something like this in your custom JavaScript code : 

```js
document.addEventListener("robservable-chart-fulfilled", (event) => {         
   d3.selectAll("#instance path")
    .on("mouseover", (event, d) => {d3.select(event.target).style("stroke", "black")})
    .on("mouseout", (event, d) => {d3.select(event.target).style("stroke", "white")});
}, false)
``` 
When you have time, could you please test it and tell me if it's working ? Thanks !

**Comment by draben** [comment]
Success!  Thank you very much for tracking down and implementing a solution to this.  Excellent work.

**Comment by juba** [comment]
Glad to hear it ! And thank your for your feedback.
