### ISSUE TITLE
setting style on unfound element

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#4]
Setting the style in [lines](https://github.com/juba/robservable/blob/master/inst/htmlwidgets/robservable.js#L35-L36) gives me an error when in Shiny since there is no `htmlwidget_container`.

```
document.getElementById('htmlwidget_container').style["display"] = "none";
document.querySelector('body').style["overflow"] = "auto";
```

I'll submit a pull.

**Comment by juba** [comment]
Closing it as I think it should be fixed. One problem was that I attached the widget to `<body>` instead of `el` :woman_facepalming:
