### ISSUE TITLE
Update runtime to include Inputs?

### ISSUE THREAD

**Issue by draben** [juba/robservable#42]
Hi,

Hard to describe this, so please bear with me.  We have robservable calls to notebooks that render tables that recently stopped working.  I suspect this is because the observable runtime now supports the `Inputs` object natively, whereas in the past notebook authors had to import via, for example `import {Table} from @observablehq/inputs`.

Our Rmd and robservable calls haven't changed, though now we receive an error:  `RuntimeError:  Inputs is not defined`

Could the dependencies of robservable be updated in such a way where the `Inputs` object is defined?

Thanks in advance!

**Comment by juba** [comment]
Hi,

I just updated the Observable runtime to the latest version (4.10.0). When you have time, could you check if it is enough to solve your problem ?

Thanks for taking the time to report the issue.

**Comment by draben** [comment]
That did it!  Thank you for such a quick fix.
