### ISSUE TITLE
Is it possible for fine-tuned control of where cells/instances of a notebook are placed?

### ISSUE THREAD

**Issue by mdlama** [juba/robservable#47]
My desired use-case is to embed cells within a flexdashboard, with the inputs in one column and the plot in another. Here's the observable script I am using:

https://observablehq.com/@eea514dd4c55b7e1/bar-charts-animal-frequency-beteween-categories

On ObservableHQ, if I choose "Embed cells" and "Runtime with JavaScript" (which I believe is what the package is using), I get:

```html
<div id="observablehq-plot-cc91335b"></div>
<div id="observablehq-viewof-species-cc91335b"></div>
<div id="observablehq-viewof-contVar-cc91335b"></div>
<p>Credit: <a href="https://observablehq.com/@eea514dd4c55b7e1/bar-charts-animal-frequency-beteween-categories">Bar Charts - animal frequency beteween categories by Drew LaMar</a></p>

<script type="module">
import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js";
import define from "https://api.observablehq.com/@eea514dd4c55b7e1/bar-charts-animal-frequency-beteween-categories.js?v=3";
new Runtime().module(define, name => {
  if (name === "plot") return new Inspector(document.querySelector("#observablehq-plot-cc91335b"));
  if (name === "viewof species") return new Inspector(document.querySelector("#observablehq-viewof-species-cc91335b"));
  if (name === "viewof contVar") return new Inspector(document.querySelector("#observablehq-viewof-contVar-cc91335b"));
  return ["species_filt","plotData"].includes(name);
});
</script>
```

What I basically am looking for is an `robservable` way to do something like the following:

```r
---
title: "Serengeti Case Study"
output: flexdashboard::flex_dashboard
---

Column 
-----------------------------------
<div id="observablehq-viewof-species-cc91335b"></div>
<div id="observablehq-viewof-contVar-cc91335b"></div>

Column
-----------------------------------
<div id="observablehq-plot-cc91335b"></div>
```

Hope that makes sense! Thanks for creating a great package!

**Comment by juba** [comment]
Do you need to interact with your embedded notebook via R code ? Or are you just embedding it in an Rmarkdown document ?

**Comment by mdlama** [comment]
Just embedding in an Rmarkdown document. No interactivity with R code needed at this stage.

**Comment by juba** [comment]
Well in this case, you could just use the Embed JavaScript feature you already described, I think you could embed the code in your RMarkdown document if you only plan to generate HTML. So you wouldn't really need `robservable`.

`robservable` would be useful if you'd like to use a notebook directly as graphics output, or in a Shiny app.

**Comment by mdlama** [comment]
Yeah, I've tried a few ways to embed the javascript, but my newbie-ness with JS is tripping me up. No matter what I try, I keep getting, e.g.,  `plot = RuntimeError: invalid module`. 

I'll keep trying some stuff. Thanks for your help!

**Comment by mdlama** [comment]
Yeah, I tried that. I was able to get it working by using Promises, as I *think* what was going on was the code creating the Runtime module was running before the observable app was fully loaded. In using JS with RMarkdown and Shiny apps, I frequently run into the need to use `$(document).ready()` or `DOMContentLoaded` events in my HTMLWidgets. This is the first time Promises have been useful to fix these race conditions, though. I wonder if flexdashboard was causing some of the issues, in particular since you were able to get it working.

**Comment by juba** [comment]
The following document seems to render correctly here :

```html
---
title: "Serengeti Case Study"
output: flexdashboard::flex_dashboard
---

<div id="observablehq-plot-cc91335b"></div>
<div id="observablehq-viewof-species-cc91335b"></div>
<div id="observablehq-viewof-contVar-cc91335b"></div>
<p>Credit: <a href="https://observablehq.com/@eea514dd4c55b7e1/bar-charts-animal-frequency-beteween-categories">Bar Charts - animal frequency beteween categories by Drew LaMar</a></p>

<script type="module">
import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js";
import define from "https://api.observablehq.com/@eea514dd4c55b7e1/bar-charts-animal-frequency-beteween-categories.js?v=3";
new Runtime().module(define, name => {
  if (name === "plot") return new Inspector(document.querySelector("#observablehq-plot-cc91335b"));
  if (name === "viewof species") return new Inspector(document.querySelector("#observablehq-viewof-species-cc91335b"));
  if (name === "viewof contVar") return new Inspector(document.querySelector("#observablehq-viewof-contVar-cc91335b"));
  return ["species_filt","plotData"].includes(name);
});
</script>
```

**Comment by mdlama** [comment]
Ah, got it. Works for me as well. I was putting the code in a js chunk, which was causing issues. Thanks for your help!
