### ISSUE TITLE
Shiny Example Not Working

### ISSUE THREAD

**Issue by jcampbell-rf** [juba/robservable#49]
First off great project!

For me, the first shiny app example is not working. In the first ("Basic Usage") example the data is not updating even on the initial load (I first thought it was just not responsive to the input$year). 

https://juba.github.io/robservable/articles/shiny.html

Thanks!

**Comment by juba** [comment]
You're right, the shiny examples weren't working anymore due to the original notebooks being modified.

This should now be fixed in the development version.

Thanks for taking the time to report the issue !

**Comment by jcampbell-rf** [comment]
Thanks!
