### ISSUE TITLE
Shiny observers

### ISSUE THREAD

**Issue by timelyportfolio** [juba/robservable#5]
I think it would be very nice to be able to communicate observable variable changes back to Shiny.  After a little playing around, I believe I found a way to achieve.  If you are ok with it, I'll submit a pull.

**Comment by timelyportfolio** [comment]
Here is an example with #6.

```
# remotes::install_github("timelyportfolio/robservable")
library(robservable)
library(htmltools)
library(shiny)

shinyApp(
  ui = tagList(
    textOutput("texta"),
    robservableOutput("robs")
  ),
  server = function(input, output, session) {
    output$robs <- renderRobservable({
      robservable(
        "@jashkenas/inputs",
        # observers outside of shiny will only print to JavaScript console
        observers = "a"
      )
    })
    
    output$texta <- renderText({input$robs_observer_a})
    
    observeEvent(input$robs_observer_a, {
      print(input$robs_observer_a)
    })
  }
)
```

**Comment by juba** [comment]
PR merged, thanks ! I'll let this issue open not to forget I should document this.

**Comment by juba** [comment]
@timelyportfolio Is it ok for you if I add you in the Authors@R package field in the following way (that's what I used in the `scatterD3` package) ?

```
person(
     "Kent", "Russell"
      , role = c("aut", "ctb")
      , email = "kent.russell@timelyportfolio.com"
)
```

**Comment by timelyportfolio** [comment]
@juba completely up to you, but sure definitely fine to add me and I would be honored.

**Comment by juba** [comment]
Done !

A small question on your observer implementation : by default the created Shiny `input` names make perfect sense to avoid collisions, but I found a bit hard to find and remember how they are built without looking at the source code.

I wonder if we could give these `input` by default just the name of the observed notebook cell, while letting the option to the user to provide its own name by using a named list in `observers` ?

Do you think it is a good idea ?

**Comment by timelyportfolio** [comment]
@juba Your point is very valid.  We could simplify by removing the `_observer_` part since it is unnecessary.  We'll still need something like `_observable_` in the notebook to avoid potential overwrite but this can be removed from the Shiny input.

I really like the idea of a named list and I'll be happy to try to prototype.  Currently, I think the way it is written support Shiny `modules`.  If named list, then I think we lose this support.

**Comment by timelyportfolio** [comment]
In quickly trying to integrate the observer, I used `class` which I realize after a little thought could be replaced with a simple `object`.

Also, I think now in Shiny, if we update rather than render we will duplicate observers.  I'll check this and fix if so.

**Comment by timelyportfolio** [comment]
Here is some code that verifies observers working in Shiny modules.

# vector
```
library(shiny)
library(robservable)

moduleUI <- function(id) {
  ns <- NS(id)
  robservableOutput(ns("map"))
}
module <- function(input, output, session) {
  output$map <- renderRobservable({

      robservable(
          "@jashkenas/inputs",
          cell = c("worldMapCoordinates", "viewof worldMap1"),
          hide = "worldMapCoordinates",
          observers = "worldMap1"
      )

  })
  
  observeEvent(input$map_worldMap1, {
    print(input$map_worldMap1)    
  })

}

ui <- div(
  h3("module robservable"),
  moduleUI("module")
)
server <- function(input, output, session) {
  callModule(module, "module")
  
  # check to make sure namespaced
  #  should not show up
  observeEvent(input$map_worldMap1, {
    print("don't want to see this")
  })
}
shinyApp(ui,server)
```

# named list
```
library(shiny)
library(robservable)

moduleUI <- function(id) {
  ns <- NS(id)
  robservableOutput(ns("map"))
}
module <- function(input, output, session) {
  output$map <- renderRobservable({

      robservable(
          "@jashkenas/inputs",
          cell = c("worldMapCoordinates", "viewof worldMap1"),
          hide = "worldMapCoordinates",
          observers = list(points = "worldMap1")
      )

  })
  
  observeEvent(input$map_points, {
    print(input$map_points)    
  })

}

ui <- div(
  h3("module robservable"),
  moduleUI("module")
)
server <- function(input, output, session) {
  callModule(module, "module")
  
  # check to make sure namespaced
  #  should not show up
  observeEvent(input$map_points, {
    print("don't want to see this")
  })
}
shinyApp(ui,server)

**Comment by juba** [comment]
Ah, now I understand why you prefixed the observer names with `el.id`, I didn't think of modules at all !

I just merged your PR after refactoring it just a bit to avoid the observer creation code duplication, I hope you won't mind.

Thanks !

**Comment by timelyportfolio** [comment]
I'm ok closing if you are.

**Comment by juba** [comment]
I'll let this issue open once again just to remember to document the named list behavior, but I'll close it after.
