### ISSUE TITLE
Better resize handling

### ISSUE THREAD

**Issue by juba** [juba/robservable#8]
For now either the width is fixed, or the widget depends on the size of the page width, and this causes problems in shiny or rmarkdown.

See if there is a way to improve this.

**Comment by juba** [comment]
This also causes problem with font sizes. For this example by @timelyportfolio and adding a fixed width, font size is almost not readable. That's because font-size on the original notebook as been set with a width of about 900px.

```r
library(robservable)
library(treemap)
library(d3r)
library(dplyr)

robservable(
  "@d3/zoomable-treemap",
  cell = "chart",
  input = list(
    data = data.frame(Titanic) %>%
      select(Class,Age,Survived,Sex,Freq) %>%
      rename(value = Freq) %>%
      d3_nest(value_cols="value", root="titanic") 
  ),
  width = 600
)
```

**Comment by timelyportfolio** [comment]
It seems the primary difficulty here is that observablehq authors likely will not design notebooks with an established standard for size and resize.  While `height` and `width` seems common, I don't think we can depend on this.  Perhaps, we could add an option/argument to pass `height` and `width` in the widget `resize` to notebook variables through a named list.  Or we can also attempt to document and illustrate how someone could fork a notebook to handle this in a more htmlwidget-like manner.

**Comment by juba** [comment]
I made some experiments and I think that indeed, systematically updating `width` and `height` variables from either `width` and `height` R arguments or `el.width` and `el.height` solves some issues. 

`width` always exist as it is defined by observable standard library (but is overriden if we redefine a `width` variable). `height` doesn't always exist, so there is a point here to update it systematically or not (as it could be used as a variable for something else than a chart height).

Updating new `width` and `height` values in `resize` seems to work, too.

I'll submit a PR as soon as the current refactoring is sorted out (sorry the repo is a bit of a mess right now...).

**Comment by juba** [comment]
See #19

**Comment by juba** [comment]
PR merged, closing this for now.
